### ISSUE TITLE
How to retrieve rating value

### ISSUE THREAD

**Issue by avinashramireddy-rapidd** [messier16/Forms.Controls#11]
Hi,
This plugin is very very helpful.
But somehow I am unable to retrieve rating value after clicking on star.
I tried PropertyChanged event. But it's not hitting when I click on star image.
I downloaded git sample and checked. It's not changing it's value there when rating value is changed
Could anyone help me with this?

=====update====================
I just checked that it's working for IOS. But in droid project, I noticed that in `RatingBarRenderer OnElementPropertyChanged function is commented.`
May be that's why it's not working of droid.

Also in Messier16RatingBar class Rating is not public.

EDStarRating is only present in IOS. What about Droid?

**Comment by fferegrino** [comment]
Yeah, I'm developing this plugin as the requirements of a project I'm developing evolve. But I've pushed an update that I think is going to solve your issue. Pleache check it and tell me if it works for you.
