### ISSUE TITLE
Command Triggering

### ISSUE THREAD

**Issue by IeuanWalker** [messier16/Forms.Controls#4]
Hi,

I want to use your checkbox control instead of the default switch. At the moment I am binding a boolean to the 'IsToggled' and using the 'Toggled' parameter to trigger an action whenever the switch is toggled.

Is there a way to have the same result using the checkboxes, because at the moment I'm using the 'Checked' parameter to bind the boolean, but cannot figure out how to trigger an action when it is checked. 

Thanks.

**Comment by libin85** [comment]
@IeuanWalker : did u get this working?

**Comment by IeuanWalker** [comment]
Nope, well sort of, at the moment I have a checkbox and a switch binding to the same Boolean (Checked/ IsToggled) and I have the Toggled property of the switch pointing to a method.

I have hidden the switch (IsVisable) so when the checkbox is checked (or unchecked) it toggles the hidden switch and causes the Toggled method to trigger.

**Comment by fferegrino** [comment]
@IeuanWalker are you using an MVVM framework?

**Comment by IeuanWalker** [comment]
@fferegrino I'm using the MVVM design but I'm not using any specific framework

**Comment by IeuanWalker** [comment]
Closing as no longer using this package
