### ISSUE TITLE
Error with building the Android project

### ISSUE THREAD

**Issue by pvhd** [messier16/Forms.Controls#5]
I got this error when building the Android project after adding the reference 0.2.2:

1>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1410,2): error : Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Messier16.Forms.Android.Controls, Version=0.2.2.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
1>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1410,2): error : File name: 'Messier16.Forms.Android.Controls.dll'
1>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1410,2): error :    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
1>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1410,2): error :    at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
1>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1410,2): error :    at Xamarin.Android.Tasks.ResolveAssemblies.Execute()

I noticed that the reference file Messier16.Forms.Droid.Controls.dll was marked yellow icon, so I had to remove it and manually added it back using the browser. I used this command in the Package Manager Console: "Install-Package Messier16.Forms.Controls" to add the reference. Do you know why this issue happened?

**Comment by fferegrino** [comment]
Did adding the reference manually solved the issue?

I'm having this issue in my own apps using my own plugin, so, you are not alone :P

**Comment by pvhd** [comment]
Yes, you would have to add the reference manually to solve the issue. I've attached the dll file for you. Please extract and put it into packages\Messier16.Forms.Controls.0.2.2\lib\MonoAndroid10 and reference it.


[Messier16.Forms.Android.Controls.zip](https://github.com/messier16/Forms.Controls/files/726854/Messier16.Forms.Android.Controls.zip)

**Comment by FLechantre** [comment]
Renaming the originial dll and reassigning the reference made the trick so you're probably right about the naming issue.

**Comment by pvhd** [comment]
Great!

**Comment by fferegrino** [comment]
I'll try to fix it from source so that doing things manually won't be
necessary.
Thanks.

**Comment by fferegrino** [comment]
As a follow up: I think this issue is solved with https://github.com/messier16/Forms.Controls/commit/7ba03b38dc42a926db54cc53120b511d86b4d4fd

It had something to do with the library being renamed when creating the nuget package.
