### ISSUE TITLE
Is there anyway to uncheck the previous checkbox if the current checkbox is checked?

### ISSUE THREAD

**Issue by pvhd** [messier16/Forms.Controls#6]
I'm using listview with checkbox and would like to know if there is anyway to achieve this. Thanks in advance.

**Comment by fferegrino** [comment]
Sorry, I do not understand your question.

Just guessing here: You want to alter the state of one checkbox depending on the state of another?

**Comment by pvhd** [comment]
Yes you got me. I would like to alter the state of one checkbox depending on the state of another. I was trying to make it work by using the CheckChanged event, but it didn't work in a listview where every row contains a checkbox. Do you have any idea about this? Thanks in advance.

**Comment by fferegrino** [comment]
Oh, I don't meant to be rude mate, but here is not the right place to ask such question as it is not directly related to the actual code of the controls. 

As this is the first time this happens I'll try you guide you to a resource that may be helpful to you: http://thatcsharpguy.com/post/multiselect-listview-mvvm-en/ basically you'll need to create a helper class that contains a boolean bindable property (like SelectableItemWrapper in the article I posted) then you'll need to keep a reference to the collection of elements bound to your list and whenever the state of one of the check boxes state changes you'll have to modify every single item in your collection, one by one.

Having said that I'll close this issue and I'd happily be reachable at feregrino at thatcsharpguy.com where I'll try to help if you still have doubts.

:)
