### ISSUE TITLE
CheckBox text

### ISSUE THREAD

**Issue by Mati182** [messier16/Forms.Controls#7]
There's a way to put the text of the checkbox? I tried with the classic chk.Text but it didn't worked

**Comment by gcadmes** [comment]
It appears there are no accommodations via iOS or Android renderers.
You can achieve the same result by putting a Label control on either side of the checkbox.

**Comment by fferegrino** [comment]
Sorry for the late response. And yes, as previously stated, there is no way to set text directly on the checkbox, you'll have to implement that yourself.
