### ISSUE TITLE
CheckboxBackgroundColor does not work

### ISSUE THREAD

**Issue by LukasThijs** [messier16/Forms.Controls#7]
Hey,

First of all great package 👍  I want to add that on Android when trying to set the checkboxbackgroundcolor or the tickcolor it does not change at all.

It does change to my accent color which is set inside my XML but still I hope you can take a look into this issue :)

Cheers,

Luuk

**Comment by fferegrino** [comment]
Sorry for the late response. Yes, it can be changed vía the styles.xml file. When I created this package I didn't knew how to override the colors, but now I think I can. I'm adding it in a future release.

:)

**Comment by pvhd** [comment]
Also the checkboxbackgroundcolor on iOS can't be changed. Could you please look into it?

Thanks,

**Comment by dheerajawale** [comment]
Thanks for this great Renderer. Once color starts working, It would be perfect

**Comment by fferegrino** [comment]
Can you please help me test this update in your apps? I have already added support for Checkbox color for both platforms but I'm afraid that in Android it may be a breaking change.

You need to install https://www.nuget.org/packages/Messier16.Forms.Controls/0.5.0-pre which is a pre-release package.

**Comment by dheerajawale** [comment]
Sure. I will let you know.Thank you for this. :)

Regards,Dheeraj D. Awale

On Thursday, April 27, 2017, 6:37:15 PM GMT+5:30, Antonio Feregrino <notifications@github.com> wrote:
Can you please help me test this update in your apps? I have already added support for Checkbox color for both platforms but I'm afraid that in Android it may be a breaking change.

You need to install https://www.nuget.org/packages/Messier16.Forms.Controls/0.5.0-pre which is a pre-release package.

**Comment by dheerajawale** [comment]
Hi,
On android it is still not working.
I have changed color to: CheckboxBackgroundColor="Green"PFA image of app
Thanks,Regards,Dheeraj D. Awale

On Thursday, April 27, 2017, 8:10:24 PM GMT+5:30, Dheeraj Awale <dheeraj.awale@ymail.com> wrote:Sure. I will let you know.Thank you for this. :)

Regards,Dheeraj D. Awale

On Thursday, April 27, 2017, 6:37:15 PM GMT+5:30, Antonio Feregrino <notifications@github.com> wrote:
Can you please help me test this update in your apps? I have already added support for Checkbox color for both platforms but I'm afraid that in Android it may be a breaking change.

You need to install https://www.nuget.org/packages/Messier16.Forms.Controls/0.5.0-pre which is a pre-release package.

**Comment by dheerajawale** [comment]
one more image showing the actual code:


Regards,Dheeraj D. Awale

On Friday, April 28, 2017, 11:16:55 AM GMT+5:30, Dheeraj Awale <dheeraj.awale@ymail.com> wrote:Hi,
On android it is still not working.
I have changed color to: CheckboxBackgroundColor="Green"PFA image of app
Thanks,Regards,Dheeraj D. Awale

On Thursday, April 27, 2017, 8:10:24 PM GMT+5:30, Dheeraj Awale <dheeraj.awale@ymail.com> wrote:Sure. I will let you know.Thank you for this. :)

Regards,Dheeraj D. Awale

On Thursday, April 27, 2017, 6:37:15 PM GMT+5:30, Antonio Feregrino <notifications@github.com> wrote:
Can you please help me test this update in your apps? I have already added support for Checkbox color for both platforms but I'm afraid that in Android it may be a breaking change.

You need to install https://www.nuget.org/packages/Messier16.Forms.Controls/0.5.0-pre which is a pre-release package.

**Comment by dheerajawale** [comment]
After successful rebuild CheckboxBackgroundColor is working on android as well.
Only TickColor is not working. But that's okay.
Thanks.

**Comment by fferegrino** [comment]
Well, implementing TickColor didn't make much sense to me :P, I'll look for ways to make it work and look nice.

Meanwhile, I'm glad it worked ;)
