### ISSUE TITLE
On UWP exception is generated when page with checkbox is being closed

### ISSUE THREAD

**Issue by johnslaby** [messier16/Forms.Controls#8]
I have found an issue with the UWP checkbox where a null exception is being thrown when the page is being closed. The problem is that the OnElementChanged method unconditionally creates a new CheckBox native control if the Coltrol property is null. When the page is being closed and the OnElementChanged method is called, the Control is null but SetNativeControl will fail and throw an exception. I have a proposed fix:

```
        protected override void OnElementChanged(ElementChangedEventArgs<Checkbox> e)
        {
            base.OnElementChanged(e);

            if (e.OldElement != null)
            {
                // Unsubscribe from event handlers and cleanup any resources
                if (Control != null)
                {
                    Control.Checked -= CheckBoxChecked;
                    Control.Unchecked -= CheckBoxUnchecked;
                }
            }

            if (e.NewElement != null)
            {
                // Configure the control and subscribe to event handlers
                if (Control == null)
                {
                    var checkBox = new CheckBox();
                    checkBox.IsThreeState = false;
                    SetNativeControl(checkBox);
                }

                // You should only create the control once (if Control is null), 
                // and then you should apply the values of NewElement to that control every time that NewElement is not null. Something like this:
                // from: https://forums.xamarin.com/discussion/comment/107477/#Comment_107477
                SetSize(e.NewElement.WidthRequest);
                Control.IsChecked = e.NewElement.Checked;
                Control.IsEnabled = e.NewElement.IsEnabled;

                Control.Checked += CheckBoxChecked;
                Control.Unchecked += CheckBoxUnchecked;
            }
        }

```
If the oldElement is not null but the Control is null, we don't attempt to deregister the event handers. If newElement is not null, but Coltrol is null, we create the native control and set it active. This appears to be similar to the way it is handeled with your iOS implementation.

**Comment by fferegrino** [comment]
Sorry, I didn't had an UWP-enabled platform to work trough this. I will this week, but if you want to send a pull request I'd gladly accept it.

**Comment by johnslaby** [comment]
I'll get you a pull request.
Thanks,
John

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by fferegrino** [comment]
Thank you!
